var TEMPERATURE_COEF_NEAR_FLAME = 0.0008;
var TEMPERATURE_COEF_OPEN_AIR = 0.04;
var TEMPERATURE_COEF_CLOSED_BALLOON = 0.005;
var SPEED_COEF = 0.5;
var WIND_COEF = 0.01 * SPEED_COEF;
var TEMPERATURE_TO_SPEED_COEF = 0.02;
var G = 0.79;